const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const db=require('../lib/attribution-db');
const booking=require('../lib/attribution-booking');
const {bookingPath}=require('../lib/attribution-http');
function fixture(){const input={bookingId:randomUUID(),startTime:new Date(Date.now()+86400000).toISOString(),timezone:'America/Toronto'};const context={id:randomUUID(),cycle_id:randomUUID(),contact_id:randomUUID(),ghl_contact_id:'ghl-person',crm_status:'delivered',attribution:{firstTouch:{source:'meetup'},latestTouch:{source:'google'}}};return {input,context,event:{id:'appointment-1',locationId:'3mi3YQaZvtUMZzaQUuL6',calendarId:'kQHIe9WY8PjSAl11jSjc',contactId:'ghl-person',startTime:input.startTime,appointmentStatus:'confirmed',dateUpdated:new Date().toISOString()}};}
async function isolated(fn){const oldEnv={...process.env},oldFetch=global.fetch,original={transaction:db.transaction,query:db.query,saveAppointment:db.saveAppointment};Object.assign(process.env,{GHL_SYNC_ENABLED:'true',GHL_BOOKING_ENABLED:'true',GHL_PRIVATE_INTEGRATION_TOKEN:'test-only',GHL_CALENDAR_IDS:'kQHIe9WY8PjSAl11jSjc',HANDOFF_SECRET:'x'.repeat(32)});delete process.env.GHL_BOOKING_NOTIFICATIONS_ENABLED;try{await fn();}finally{global.fetch=oldFetch;Object.assign(db,original);for(const k of Object.keys(process.env))if(!(k in oldEnv))delete process.env[k];Object.assign(process.env,oldEnv);}}
const ok=data=>({ok:true,json:async()=>data});
test('signed context rejects tampering and booking cannot accept contact/owner overrides',()=>isolated(async()=>{const {input,context}=fixture();const path=bookingPath(context.id),ref=new URL(path,'https://example.com').searchParams.get('ref');assert.equal(booking.claimFor(ref).id,context.id);assert.throws(()=>booking.claimFor(ref+'x'));const payload=booking.appointmentPayload(context,{...input,contactId:'attacker',calendarId:'other',assignedUserId:'jason'});assert.equal(payload.contactId,'ghl-person');assert.equal(payload.calendarId,'kQHIe9WY8PjSAl11jSjc');assert.equal(payload.assignedUserId,undefined);assert.equal(payload.ignoreFreeSlotValidation,false);assert.equal(payload.ignoreDateRange,false);assert.equal(payload.toNotify,false);}));
test('slot ranges reject excessive range and invalid timezone; unsynced contact cannot book',()=>isolated(async()=>{assert.throws(()=>booking.range({startDate:Date.now(),endDate:Date.now()+32*86400000,timezone:'America/Toronto'}));assert.throws(()=>booking.range({startDate:Date.now(),endDate:Date.now()+86400000,timezone:'Bogus/Timezone'}));const {context}=fixture();assert.throws(()=>booking.requireBooking({...context,crm_status:'pending'}),{message:'contact_sync_pending'});}));
test('booking reports success only after provider read-back matches the immutable server context',()=>isolated(async()=>{
  const {input,context,event}=fixture(),calls=[],writes=[];let saved;
  db.transaction=async fn=>fn({query:async()=>({rows:[],rowCount:0})});db.query=async(sql,params)=>{writes.push({sql,params});return {rows:[]}};db.saveAppointment=async value=>{saved=value};
  global.fetch=async(url,options)=>{calls.push({url,options});if(url.includes('/contacts/'))return ok({events:[]});if(url.includes('/free-slots'))return ok({[input.startTime.slice(0,10)]:{slots:[input.startTime]}});if(options.method==='POST')return ok({id:event.id});return ok({event});};
  const result=await booking.book(context,input);assert.equal(result.booked,true);assert.equal(calls.filter(x=>x.options.method==='POST').length,1);assert.equal(calls.at(-1).options.method,'GET');assert.equal(saved.applicationId,context.id);assert.deepEqual(saved.attribution,context.attribution);assert.equal(saved.bookingSetterId,null);assert.ok(writes.some(x=>x.sql.includes("state='confirmed'")));
}));
test('provider conflict cannot claim booked; availability checks prevent create',()=>isolated(async()=>{const {input,context}=fixture();let posts=0;db.transaction=async fn=>fn({query:async()=>({rows:[],rowCount:0})});db.query=async()=>({rows:[]});global.fetch=async(url,options)=>{if(options.method==='POST')posts++;return ok(url.includes('/contacts/')?{events:[]}:{});};await assert.rejects(booking.book(context,input),{message:'slot_unavailable',status:409});assert.equal(posts,0);}));
test('duplicate confirmed booking returns same verified appointment without a second create',()=>isolated(async()=>{const {input,context,event}=fixture();let posts=0;db.transaction=async fn=>fn({query:async sql=>({rows:sql.startsWith('SELECT * FROM sog_booking_intents')?[{id:input.bookingId,application_id:context.id,start_time:input.startTime,state:'confirmed',appointment_id:event.id}]:[],rowCount:0})});db.query=async()=>({rows:[]});db.saveAppointment=async()=>{};global.fetch=async(url,options)=>{if(options.method==='POST')posts++;return ok({event})};assert.equal((await booking.book(context,input)).appointmentId,event.id);assert.equal(posts,0);}));
test('ambiguous provider timeout becomes uncertain; retry reconciles without re-posting',()=>isolated(async()=>{
  const {input,context}=fixture();let posts=0,states=[];let existing;
  db.transaction=async fn=>fn({query:async sql=>({rows:sql.startsWith('SELECT * FROM sog_booking_intents')&&existing?[existing]:[],rowCount:0})});db.query=async(sql,params)=>{if(sql.includes('SET state=$2'))states.push(params[1]);return {rows:[]}};
  global.fetch=async(url,options)=>{if(url.includes('/contacts/'))return ok({events:[]});if(url.includes('/free-slots'))return ok({[input.startTime.slice(0,10)]:{slots:[input.startTime]}});if(options.method==='POST'){posts++;throw new Error('network timeout');}throw new Error('unexpected');};
  assert.equal((await booking.book(context,input)).pending,true);assert.deepEqual(states,['uncertain']);existing={id:input.bookingId,application_id:context.id,start_time:input.startTime,state:'uncertain'};assert.equal((await booking.book(context,input)).booked,false);assert.equal(posts,1);
}));
test('read-back with another contact fails verification rather than assigning their appointment',()=>isolated(async()=>{const {input,context,event}=fixture();global.fetch=async()=>ok({event:{...event,contactId:'someone-else'}});await assert.rejects(booking.verifyAppointment(event.id,context,input),{message:'booking_verification_pending'});}));
test('same-slot legacy appointment is not attributed to the new application',()=>isolated(async()=>{const {input,context,event}=fixture();global.fetch=async(url)=>ok(url.includes('/contacts/')?{events:[event]}:{event:{...event,description:'Original booking from another channel'}});await assert.rejects(booking.reconcile(context,input),{message:'appointment_already_exists',status:409});}));
