const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const {application,event,touch,mergeTouches,nextStage,appointment,secureEqual}=require('../lib/attribution');
const {bookingPath,authorize}=require('../lib/attribution-http');
const valid=()=>({submissionId:randomUUID(),journeyId:randomUUID(),quizVersion:'apprentice-v1',contact:{email:'Person@Example.com',firstName:'Person'},consent:{privacy:true,marketing:false},answers:{ageRange:'30_39',goals:['build_system'],weeklyTime:'3_5_hours',educationBudget:'not_ready',attendance:'unsure'}});
test('application validates all required quiz answers and normalizes identity',()=>{const v=application(valid());assert.equal(v.contact.email,'person@example.com');assert.deepEqual(v.answers.goals,['build_system']);assert.equal(v.consent.marketing,false);assert.throws(()=>application({...valid(),answers:{}}));assert.throws(()=>application({...valid(),consent:{privacy:false}}));assert.throws(()=>application({...valid(),quizVersion:'fake'}));});
test('public application cannot assign owners, affiliate credit or booking state',()=>{const v=application({...valid(),assignedTo:'jason',bookingSetterId:'jason',status:'booked'});assert.equal(v.status,undefined);assert.equal(v.assignedTo,undefined);assert.equal(v.bookingSetterId,undefined);assert.equal(nextStage({status:'won',stage:'won'},'cancelled'),'won');});
test('first attribution immutable; later direct visit cannot overwrite last non-direct',()=>{const now=new Date();const initial={firstTouch:touch({utm_source:'meetup'},now),latestTouch:touch({utm_source:'meetup'},now)};const direct={firstTouch:touch({},now),latestTouch:touch({},now)};assert.deepEqual(mergeTouches(initial,direct),initial);const ads={firstTouch:touch({utm_source:'google'},now),latestTouch:touch({utm_source:'google'},now)};const result=mergeTouches(initial,ads);assert.equal(result.firstTouch.source,'meetup');assert.equal(result.latestTouch.source,'google');});
test('stale attribution cannot replace a newer acquisition; URL queries stripped',()=>{const now=new Date();const latest=touch({utm_source:'youtube',captured_at:now.toISOString()});const stale=touch({utm_source:'facebook',captured_at:new Date(now-10000).toISOString()});assert.equal(mergeTouches({firstTouch:latest,latestTouch:latest},{firstTouch:stale,latestTouch:stale}).latestTouch.source,'youtube');assert.equal(touch({landing_page:'https://example.com/apply?email=private@example.com#secret'}).landing_page,'https://example.com/apply');});
test('public analytics cannot invent appointments or sales',()=>{assert.throws(()=>event({eventId:randomUUID(),journeyId:randomUUID(),type:'appointment_confirmed',path:'/book'}));assert.throws(()=>event({eventId:randomUUID(),journeyId:randomUUID(),type:'page_view',path:'/book?email=x'}));});
test('booking webhook requires real event identity/location/calendar/status',()=>{assert.throws(()=>appointment({eventId:randomUUID(),locationId:'wrong',status:'confirmed'}));assert.equal(nextStage({status:'open',stage:'call_held'},'confirmed'),'call_held');assert.equal(nextStage({status:'open',stage:'unbooked'},'confirmed'),'booked');});
test('constant time authentication fails closed; handoff has no email',()=>{assert.equal(secureEqual('secret','secreT'),false);const old=process.env.GHL_EVENTS_SECRET;process.env.GHL_EVENTS_SECRET='a'.repeat(32);assert.throws(()=>authorize({headers:{authorization:'Bearer wrong'}},'GHL_EVENTS_SECRET'));authorize({headers:{authorization:'Bearer '+'a'.repeat(32)}},'GHL_EVENTS_SECRET');if(old===undefined)delete process.env.GHL_EVENTS_SECRET;else process.env.GHL_EVENTS_SECRET=old;const key=process.env.HANDOFF_SECRET;process.env.HANDOFF_SECRET='b'.repeat(32);assert.match(bookingPath(randomUUID()),/^\/book\?ref=[\w-]+\.[\w-]+$/);if(key===undefined)delete process.env.HANDOFF_SECRET;else process.env.HANDOFF_SECRET=key;});
test('disabled intake returns 503 and never reports a submission success',async()=>{const before=process.env.ATTRIBUTION_INTAKE_ENABLED;delete process.env.ATTRIBUTION_INTAKE_ENABLED;const handler=require('../api/applications');let status,payload;await handler({method:'POST',headers:{},body:valid()},{setHeader(){},status(s){status=s;return this},json(p){payload=p;return this}});assert.equal(status,503);assert.equal(payload.ok,false);if(before!==undefined)process.env.ATTRIBUTION_INTAKE_ENABLED=before;});

test('appointment statuses cannot classify an unmapped legacy sales stage',()=>{for(const status of ['new','confirmed','cancelled','showed','noshow','invalid'])assert.equal(nextStage({status:'open',stage:'legacy_review'},status),'legacy_review');});
