const test=require('node:test'),assert=require('node:assert/strict');
const {contactUpdate,FIELD_KEYS,syncApplication}=require('../lib/attribution-ghl');
const ids=Object.fromEntries(FIELD_KEYS.map(k=>[k,'field_'+k]));
const first={source:'meetup',medium:'offline',utm_campaign:'first',utm_content:'qr',utm_term:'keyword',utm_id:'campaign-id',gclid:'google-click',fbclid:'meta-click',gbraid:'braid',wbraid:'web-braid',ttclid:'tik-click',landing_page:'https://school-of-gains.com/links',referrer:'https://meetup.com/',captured_at:'2026-09-01T12:00:00Z',confidence:'explicit',model:'sog-v1'};
const latest={...first,source:'youtube',medium:'organic_social',utm_campaign:'later'};
const stored={id:'application',cycle_id:'cycle',journey_id:'journey',quiz_version:'apprentice-v1',created_at:new Date('2026-09-21T13:10:45.123Z'),answers:{ageRange:'30_39',goals:['build_system','confidence'],weeklyTime:'5_10_hours',educationBudget:'not_ready',attendance:'yes',notes:'Please discuss risk management'},consent:{privacy:true,marketing:false},attribution:{firstTouch:first,latestTouch:latest}};
const canonical={first_touch:first,latest_touch:latest};
const values=update=>Object.fromEntries(update.customFields.map(x=>[x.id.replace('field_',''),x.fieldValue]));
test('GHL snapshots preserve every captured attribution field and each quiz answer',()=>{const data=values(contactUpdate({contact:{}},stored,canonical,{customFields:[]},ids));assert.deepEqual(JSON.parse(data.first_touch_snapshot),first);assert.deepEqual(JSON.parse(data.latest_touch_snapshot),latest);const snapshot=JSON.parse(data.application_snapshot);assert.deepEqual(snapshot.answers,stored.answers);assert.deepEqual(snapshot.attribution,stored.attribution);assert.equal(snapshot.journeyId,'journey');assert.equal(data.quiz_notes,stored.answers.notes);assert.deepEqual(JSON.parse(data.quiz_goals),stored.answers.goals);});
test('consent timestamp uses durable submission time and false opt-in never changes native DND',()=>{const update=contactUpdate({contact:{firstName:'Updated',lastName:'',phone:''}},stored,canonical,{customFields:[]},ids),data=values(update);assert.equal(data.consent_recorded_at,'2026-09-21T13:10:45.123Z');assert.equal(data.marketing_consent,'false');assert.equal(data.privacy_consent,'true');assert.equal(update.firstName,'Updated');for(const key of ['lastName','phone','dnd','dndSettings','tags','assignedTo','email'])assert.equal(update[key],undefined);});
test('existing GHL first touch is not overwritten when local state is rebuilt',()=>{const remote={customFields:[{id:ids.first_source,value:'original'},{id:ids.first_touch_snapshot,fieldValue:'{"source":"original"}'},{id:ids.first_campaign,value:''}]};const data=values(contactUpdate({contact:{}},stored,canonical,remote,ids));assert.equal(data.first_source,undefined);assert.equal(data.first_touch_snapshot,undefined);assert.equal(data.first_campaign,'first');assert.equal(data.latest_source,'youtube');});
test('canonical contact first touch overrides an outbox snapshot and incomplete mapping fails',()=>{const data=values(contactUpdate({attribution:{firstTouch:{source:'tampered'}},contact:{phone:'+15555550100'}},stored,canonical,{customFields:[]},ids));assert.equal(data.first_source,'meetup');assert.throws(()=>contactUpdate({},stored,canonical,{},{}),/ghl_field_mapping_missing/);});
test('latest repeated application updates standard profile and full custom fields on the linked GHL contact',async()=>{
 const oldFetch=global.fetch,oldEnv={...process.env};Object.assign(process.env,{GHL_SYNC_ENABLED:'true',GHL_PRIVATE_INTEGRATION_TOKEN:'test',GHL_UNBOOKED_STAGE_ID:'stage',GHL_ATTRIBUTION_FIELDS_JSON:JSON.stringify(ids)});const calls=[];
 global.fetch=async(url,options)=>{calls.push({url,options});return {ok:true,json:async()=>({contact:{id:'ghl',locationId:'3mi3YQaZvtUMZzaQUuL6',email:'person@example.com',customFields:[]}})}};
 const c={query:async sql=>{if(sql.startsWith('SELECT * FROM sog_contacts'))return {rows:[{id:'local',ghl_contact_id:'ghl'}]};if(sql.startsWith('SELECT * FROM sog_sales_cycles'))return {rows:[{id:'cycle',ghl_opportunity_id:'existing'}]};if(sql.startsWith('SELECT id,created_at'))return {rows:[stored]};if(sql.startsWith('SELECT email,first_touch'))return {rows:[{...canonical,email:'person@example.com'}]};return {rows:[]};}};
 try{await syncApplication(c,{contactId:'local',cycleId:'cycle',submissionId:'application',contact:{email:'person@example.com',firstName:'New Name',phone:'+15555550100'}});assert.equal(calls.length,2);assert.equal(calls[0].options.method,'GET');const update=JSON.parse(calls[1].options.body);assert.equal(update.firstName,'New Name');assert.equal(update.phone,'+15555550100');assert.equal(update.customFields.length,22);}finally{global.fetch=oldFetch;for(const k of Object.keys(process.env))if(!(k in oldEnv))delete process.env[k];Object.assign(process.env,oldEnv);}
});

test('new opportunity creation follows successful application field sync; failed writes and stale jobs cannot create',async()=>{
 const allocator=require('../lib/attribution-assignment'),oldReserve=allocator.reserveCloser,oldFetch=global.fetch,oldEnv={...process.env};
 Object.assign(process.env,{GHL_SYNC_ENABLED:'true',GHL_PRIVATE_INTEGRATION_TOKEN:'test',GHL_UNBOOKED_STAGE_ID:'stage',GHL_ATTRIBUTION_FIELDS_JSON:JSON.stringify(ids)});
 let mode='success',calls=[];allocator.reserveCloser=async()=>{calls.push('reserve');return 'closer';};
 global.fetch=async(url,options)=>{const action=options.method+' '+new URL(url).pathname;calls.push(action);if(action==='PUT /contacts/ghl' && mode==='failed')return {ok:false,status:503};return {ok:true,json:async()=>url.includes('/contacts/')?{contact:{id:'ghl',email:'person@example.com'}}:options.method==='POST'?{opportunity:{id:'new-opp',pipelineStageId:'stage'}}:{opportunities:[]}};};
 const c={query:async sql=>{if(sql.startsWith('SELECT * FROM sog_contacts'))return {rows:[{id:'local',ghl_contact_id:'ghl'}]};if(sql.startsWith('SELECT * FROM sog_sales_cycles'))return {rows:[{id:stored.cycle_id}]};if(sql.startsWith('SELECT id,created_at'))return {rows:[{...stored,id:mode==='stale'?'newer':stored.id}]};if(sql.startsWith('SELECT email,first_touch'))return {rows:[{...canonical,email:'person@example.com'}]};return {rows:[]};}};
 const input={contactId:'local',cycleId:stored.cycle_id,submissionId:stored.id,contact:{email:'person@example.com'}};
 try{
  await syncApplication(c,input,{reserveCreation:async()=>true});assert.ok(calls.indexOf('PUT /contacts/ghl')<calls.indexOf('POST /opportunities/'));assert.equal(calls.filter(x=>x==='PUT /contacts/ghl').length,1);
  calls=[];mode='failed';await assert.rejects(syncApplication(c,input,{reserveCreation:async()=>true}),/ghl_http_503/);assert.equal(calls.includes('reserve'),false);assert.equal(calls.includes('POST /opportunities/'),false);
  calls=[];mode='stale';assert.equal((await syncApplication(c,input,{reserveCreation:async()=>true})).superseded,true);assert.deepEqual(calls,['GET /opportunities/search']);
 }finally{allocator.reserveCloser=oldReserve;global.fetch=oldFetch;for(const key of Object.keys(process.env))if(!(key in oldEnv))delete process.env[key];Object.assign(process.env,oldEnv);}
});
