const test=require('node:test'),assert=require('node:assert/strict');
const {configuration,runBatch}=require('../lib/worker-batch');
const {processOne}=require('../lib/attribution-outbox');
test('worker limits reject invalid or unbounded environment values',()=>{assert.deepEqual(configuration({}),{maxJobs:5,budgetMs:15000});assert.throws(()=>configuration({GHL_WORKER_BATCH_SIZE:'1000'}));assert.throws(()=>configuration({GHL_WORKER_BUDGET_MS:'0'}));assert.throws(()=>configuration({GHL_WORKER_BATCH_SIZE:'2.5'}));});
test('batch processes serially up to cap and never claims unlimited work',async()=>{let active=0,maximum=0,calls=0;const result=await runBatch(async()=>{active++;maximum=Math.max(maximum,active);calls++;await Promise.resolve();active--;return {processed:1};},{maxJobs:3,budgetMs:1000},()=>0);assert.equal(calls,3);assert.equal(maximum,1);assert.equal(result.processed,3);assert.equal(result.stopped,'batch_limit');});
test('batch soft deadline stops before next claim and lets current commit finish',async()=>{let time=0,committed=false;const result=await runBatch(async()=>{time=16000;committed=true;return {processed:1};},{maxJobs:5,budgetMs:15000},()=>time);assert.equal(committed,true);assert.equal(result.attempted,1);assert.equal(result.stopped,'time_budget');});
test('retry and terminal outcomes consume budget, empty queue stops without spinning',async()=>{const jobs=[{processed:0,retryQueued:true},{processed:0,needsReview:true},{processed:0,lostLease:true},{processed:0}];const result=await runBatch(async()=>jobs.shift(),{maxJobs:5,budgetMs:1000},()=>0);assert.deepEqual({...result,durationMs:0},{processed:0,attempted:3,retryQueued:1,needsReview:1,lostLease:1,stopped:'empty',durationMs:0});});
function queue(jobs){const locked=new Set(),updates=[];return {updates,transaction:async fn=>{let lock;try{return await fn({query:async(sql,args)=>{if(sql.startsWith('SELECT * FROM sog_outbox')){const row=jobs.find(x=>x.status==='pending' && !locked.has(x.id));if(row){locked.add(row.id);lock=row.id;}return {rows:row?[row]:[]};}if(/^(SAVEPOINT|ROLLBACK TO SAVEPOINT|RELEASE SAVEPOINT)/.test(sql))return {rows:[]};updates.push({sql,args});const row=jobs.find(x=>x.id===args[0]);if(sql.includes("status='delivered'"))row.status='delivered';else if(sql.includes('attempts=attempts+1')){row.attempts++;row.status=row.attempts>=10?'failed':'delayed';}else if(sql.includes("status='failed'"))row.status='failed';return {rows:[],rowCount:1};}});}finally{if(lock)locked.delete(lock);}}};}
test('overlapping outbox workers skip locked jobs and deliver each event once',async()=>{const jobs=Array.from({length:4},(_,i)=>({id:i+1,type:'application',payload:{eventId:i+1},attempts:0,status:'pending'})),db=queue(jobs),seen=[];const execute=async(c,payload)=>{seen.push(payload.eventId);await new Promise(resolve=>setImmediate(resolve));};await Promise.all([1,2].map(()=>runBatch(()=>processOne({db,syncApplication:execute}),{maxJobs:4,budgetMs:1000},()=>0)));assert.equal(seen.length,4);assert.equal(new Set(seen).size,4);assert.ok(jobs.every(x=>x.status==='delivered'));});
test('last permitted outbox attempt becomes failed rather than reporting another retry',async()=>{const jobs=[{id:1,type:'application',payload:{},attempts:9,status:'pending'}],db=queue(jobs);const result=await processOne({db,syncApplication:async()=>{throw new Error('private contact details');}});assert.equal(result.retryQueued,false);assert.equal(result.needsReview,true);assert.equal(jobs[0].status,'failed');assert.equal(db.updates.at(-1).args[1],'ghl_delivery_failed');});
test('exhausted pending job never invokes a provider and still consumes batch work',async()=>{const db=queue([{id:1,type:'application',payload:{},attempts:10,status:'pending'}]);const result=await processOne({db,syncApplication:async()=>assert.fail('must not call provider')});assert.equal(result.needsReview,true);assert.equal(result.processed,0);});
test('worker HTTP routes reject unauthorized callers and disabled flags before processing',async()=>{
 const oldEnv={...process.env};process.env.CRON_SECRET='worker-test-secret-'.padEnd(40,'x');process.env.GHL_SYNC_ENABLED='false';process.env.GHL_SIGNALS_ENABLED='false';
 try{for(const name of ['process','process-signals']){const handler=require('../api/webhooks/'+name);for(const method of ['GET','POST'])for(const [header,expected] of [['Bearer wrong',401],['Bearer '+process.env.CRON_SECRET,503]]){let status;await handler({method,headers:{authorization:header},body:{maxJobs:999999}},{setHeader(){},status(value){status=value;return this},json(){return this}});assert.equal(status,expected);}}}finally{for(const k of Object.keys(process.env))if(!(k in oldEnv))delete process.env[k];Object.assign(process.env,oldEnv);}
});
